version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    networks:
      - devenv
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ./data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    networks:
      - devenv
    restart: unless-stopped
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql

  nginx:
    image: nginx
    container_name: nginx
    networks:
      - devenv
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./virtual-hosts:/etc/nginx/conf.d
    depends_on:
      - phpmyadmin

networks:
  devenv:
    name: devenv
    driver: bridge